/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export enum AdventurerAnimation {
  // General
  DEATH_A = 'Death_A',
  DEATH_B = 'Death_B',
  HIT_A = 'Hit_A',
  HIT_B = 'Hit_B',
  IDLE_A = 'Idle_A',
  IDLE_B = 'Idle_B',
  INTERACT = 'Interact',
  PICKUP = 'PickUp',
  SPAWN_AIR = 'Spawn_Air',
  SPAWN_GROUND = 'Spawn_Ground',
  THROW = 'Throw',
  USE_ITEM = 'Use_Item',

  // Movement Basic
  JUMP_FULL_LONG = 'Jump_Full_Long',
  JUMP_FULL_SHORT = 'Jump_Full_Short',
  JUMP_IDLE = 'Jump_Idle',
  JUMP_LAND = 'Jump_Land',
  JUMP_START = 'Jump_Start',
  RUNNING_A = 'Running_A',
  RUNNING_B = 'Running_B',
  WALKING_A = 'Walking_A',
  WALKING_B = 'Walking_B',
  WALKING_C = 'Walking_C',

  // Movement Advanced
  CRAWLING = 'Crawling',
  CROUCHING = 'Crouching',
  DODGE_BACKWARD = 'Dodge_Backward',
  DODGE_FORWARD = 'Dodge_Forward',
  DODGE_LEFT = 'Dodge_Left',
  DODGE_RIGHT = 'Dodge_Right',
  RUNNING_HOLDING_BOW = 'Running_HoldingBow',
  RUNNING_HOLDING_RIFLE = 'Running_HoldingRifle',
  RUNNING_STRAFE_LEFT = 'Running_Strafe_Left',
  RUNNING_STRAFE_RIGHT = 'Running_Strafe_Right',
  SNEAKING = 'Sneaking',
  WALKING_BACKWARDS = 'Walking_Backwards',

  // Combat Ranged
  RANGED_1H_AIMING = 'Ranged_1H_Aiming',
  RANGED_1H_RELOAD = 'Ranged_1H_Reload',
  RANGED_1H_SHOOT = 'Ranged_1H_Shoot',
  RANGED_1H_SHOOTING = 'Ranged_1H_Shooting',
  RANGED_2H_AIMING = 'Ranged_2H_Aiming',
  RANGED_2H_RELOAD = 'Ranged_2H_Reload',
  RANGED_2H_SHOOT = 'Ranged_2H_Shoot',
  RANGED_2H_SHOOTING = 'Ranged_2H_Shooting',
  RANGED_BOW_AIMING_IDLE = 'Ranged_Bow_Aiming_Idle',
  RANGED_BOW_DRAW = 'Ranged_Bow_Draw',
  RANGED_BOW_DRAW_UP = 'Ranged_Bow_Draw_Up',
  RANGED_BOW_IDLE = 'Ranged_Bow_Idle',
  RANGED_BOW_RELEASE = 'Ranged_Bow_Release',
  RANGED_BOW_RELEASE_UP = 'Ranged_Bow_Release_Up',
  RANGED_MAGIC_RAISE = 'Ranged_Magic_Raise',
  RANGED_MAGIC_SHOOT = 'Ranged_Magic_Shoot',
  RANGED_MAGIC_SPELLCASTING = 'Ranged_Magic_Spellcasting',
  RANGED_MAGIC_SPELLCASTING_LONG = 'Ranged_Magic_Spellcasting_Long',
  RANGED_MAGIC_SUMMON = 'Ranged_Magic_Summon',

  // Combat Melee
  MELEE_1H_ATTACK_CHOP = 'Melee_1H_Attack_Chop',
  MELEE_1H_ATTACK_JUMP_CHOP = 'Melee_1H_Attack_Jump_Chop',
  MELEE_1H_ATTACK_SLICE_DIAGONAL = 'Melee_1H_Attack_Slice_Diagonal',
  MELEE_1H_ATTACK_SLICE_HORIZONTAL = 'Melee_1H_Attack_Slice_Horizontal',
  MELEE_1H_ATTACK_STAB = 'Melee_1H_Attack_Stab',
  MELEE_2H_ATTACK_CHOP = 'Melee_2H_Attack_Chop',
  MELEE_2H_ATTACK_SLICE = 'Melee_2H_Attack_Slice',
  MELEE_2H_ATTACK_SPIN = 'Melee_2H_Attack_Spin',
  MELEE_2H_ATTACK_SPINNING = 'Melee_2H_Attack_Spinning',
  MELEE_2H_ATTACK_STAB = 'Melee_2H_Attack_Stab',
  MELEE_2H_IDLE = 'Melee_2H_Idle',
  MELEE_BLOCK = 'Melee_Block',
  MELEE_BLOCK_ATTACK = 'Melee_Block_Attack',
  MELEE_BLOCK_HIT = 'Melee_Block_Hit',
  MELEE_BLOCKING = 'Melee_Blocking',
  MELEE_DUALWIELD_ATTACK_CHOP = 'Melee_Dualwield_Attack_Chop',
  MELEE_DUALWIELD_ATTACK_SLICE = 'Melee_Dualwield_Attack_Slice',
  MELEE_DUALWIELD_ATTACK_STAB = 'Melee_Dualwield_Attack_Stab',
  MELEE_UNARMED_ATTACK_KICK = 'Melee_Unarmed_Attack_Kick',
  MELEE_UNARMED_ATTACK_PUNCH_A = 'Melee_Unarmed_Attack_Punch_A',
  MELEE_UNARMED_IDLE = 'Melee_Unarmed_Idle',
}
