import type { BeaconObject } from '../maps/mapObjectTypes.ts';

export const BEACON_CONSTANTS = {
  DEFAULT_RADIUS: 10.4,
  DEFAULT_CAPTURE_TIME: 30.0,
  TEAM_BONUS_MULTIPLIER: 0.3,
  MAX_TEAM_BONUS_CAP: 5,
  /** How often the server syncs beacon progress to clients (ms). */
  SYNC_INTERVAL_MS: 1000,
  /** How often the server persists dirty beacon state to the database (ms). */
  PERSIST_INTERVAL_MS: 10000,
  /** Passive healing per second for owners inside a captured, non-contested beacon. */
  HEAL_PER_SECOND: 5,
} as const;

export const BEACONS: Partial<Record<string, BeaconObject[]>> = {
  mexico: [
    {
      id: 'mexico_beacon_north',
      type: 'beacon',
      name: 'Pueblos del Norte',
      position: [-16.392, 44.154, -60.285],
      groundOffset: -1,
      captureRadius: BEACON_CONSTANTS.DEFAULT_RADIUS,
      baseCaptureTime: BEACON_CONSTANTS.DEFAULT_CAPTURE_TIME,
      glb: 'Hut.glb',
    },
    {
      id: 'mexico_beacon_tenochtitlan',
      type: 'beacon',
      name: 'Tenochtitlan',
      position: [-48.487, 25.392, 128.298],
      captureRadius: BEACON_CONSTANTS.DEFAULT_RADIUS * 3,
      baseCaptureTime: 60,
      glb: 'TemploMayor.glb',
    },
    {
      id: 'mexico_beacon_monte_alban',
      type: 'beacon',
      name: 'Monte Albán',
      position: [85.533, 14.326, 197.619],
      captureRadius: BEACON_CONSTANTS.DEFAULT_RADIUS,
      baseCaptureTime: BEACON_CONSTANTS.DEFAULT_CAPTURE_TIME,
    },
    // {
    //   id: 'mexico_beacon_tulum',
    //   type: 'beacon',
    //   name: 'Tulum',
    //   position: [303.822, 14.326, 94.43],
    //   captureRadius: BEACON_CONSTANTS.DEFAULT_RADIUS,
    //   baseCaptureTime: BEACON_CONSTANTS.DEFAULT_CAPTURE_TIME,
    //   glb: 'MayanZiggurat.glb',
    // },
    {
      id: 'mexico_beacon_paquime',
      type: 'beacon',
      name: 'Paquimé',
      position: [-134.046, 34.564, -190.075],
      captureRadius: BEACON_CONSTANTS.DEFAULT_RADIUS,
      baseCaptureTime: BEACON_CONSTANTS.DEFAULT_CAPTURE_TIME,
      glb: 'Hut.glb',
    },
    {
      id: 'mexico_beacon_la_quemada',
      type: 'beacon',
      name: 'La Quemada',
      position: [-98.21, 34.563, -26.508],
      groundOffset: -1,
      captureRadius: BEACON_CONSTANTS.DEFAULT_RADIUS,
      baseCaptureTime: BEACON_CONSTANTS.DEFAULT_CAPTURE_TIME,
      glb: 'Hut.glb',
    },
    {
      id: 'mexico_beacon_las_labradas',
      type: 'beacon',
      name: 'Las Labradas',
      position: [-269.838, 34.564, -65.822],
      captureRadius: BEACON_CONSTANTS.DEFAULT_RADIUS,
      baseCaptureTime: BEACON_CONSTANTS.DEFAULT_CAPTURE_TIME,
    },
    /*
    {
      id: 'mexico_beacon_xochicalco',
      type: 'beacon',
      name: 'Xochicalco',
      position: [-25.597, 25.392, 174.515],
      captureRadius: BEACON_CONSTANTS.DEFAULT_RADIUS,
      baseCaptureTime: BEACON_CONSTANTS.DEFAULT_CAPTURE_TIME,
    },
    */
    {
      id: 'mexico_beacon_la_venta',
      type: 'beacon',
      name: 'La Venta',
      position: [131.468, 14.326, 109.175],
      captureRadius: BEACON_CONSTANTS.DEFAULT_RADIUS,
      baseCaptureTime: BEACON_CONSTANTS.DEFAULT_CAPTURE_TIME,
      glb: 'CabezaOlmeca.glb',
    },
    {
      id: 'mexico_beacon_palenque',
      type: 'beacon',
      name: 'Palenque',
      position: [195.255, 14.326, 136.145],
      captureRadius: BEACON_CONSTANTS.DEFAULT_RADIUS * 1.5,
      baseCaptureTime: BEACON_CONSTANTS.DEFAULT_CAPTURE_TIME,
      glb: 'MayanZiggurat.glb',
    },
    {
      id: 'mexico_beacon_acapulco',
      type: 'beacon',
      name: 'Acapulco',
      position: [3.969, 14.326, 221.821],
      captureRadius: BEACON_CONSTANTS.DEFAULT_RADIUS,
      baseCaptureTime: BEACON_CONSTANTS.DEFAULT_CAPTURE_TIME,
      glb: 'Port.glb',
    },
    {
      id: 'mexico_beacon_chichen_itza',
      type: 'beacon',
      name: 'Chichén Itzá',
      position: [275.388, 14.326, 63.92],
      captureRadius: BEACON_CONSTANTS.DEFAULT_RADIUS * 1.5,
      baseCaptureTime: BEACON_CONSTANTS.DEFAULT_CAPTURE_TIME,
      glb: 'MayanZiggurat.glb',
    },
    {
      id: 'mexico_beacon_san_gervasio',
      type: 'beacon',
      name: 'San Gervasio',
      position: [333.549, 25.289, 44.529],
      captureRadius: BEACON_CONSTANTS.DEFAULT_RADIUS / 2,
      baseCaptureTime: BEACON_CONSTANTS.DEFAULT_CAPTURE_TIME,
      // glb: 'MayanZiggurat.glb',
    },
    {
      id: 'mexico_beacon_guachimontones',
      type: 'beacon',
      name: 'Guachimontones',
      position: [-164.04, 25.392, 109.189],
      captureRadius: BEACON_CONSTANTS.DEFAULT_RADIUS,
      baseCaptureTime: BEACON_CONSTANTS.DEFAULT_CAPTURE_TIME,
      glb: '/models/nature/Rock_1_J_Color1.glb',
    },
    {
      id: 'mexico_beacon_baja_california',
      type: 'beacon',
      name: 'Pueblos de Baja California',
      position: [-354.162, 36.927, -10.182],
      captureRadius: BEACON_CONSTANTS.DEFAULT_RADIUS,
      baseCaptureTime: BEACON_CONSTANTS.DEFAULT_CAPTURE_TIME,
      glb: 'Hut.glb',
    },
  ],
};
