import { Hero } from '../types.ts';
import { HeroCategory } from '../../enums/HeroCategory.ts';
import { AdventurerAnimation } from '../../enums/AdventurerAnimation.ts';
import { ActionType } from '../../enums/ActionType.ts';

export const DOCTOR_HERO: Hero = {
  id: 'doctor',
  name: 'Doctor',
  race: 'Doctor',
  category: HeroCategory.TANK,
  description: 'Médico de campaña. No puede disparar mientras se cura, pero se recupera rápido.',
  stats: {
    maxHealth: 150,
    moveSpeed: 6.0,
    hitboxSize: 1.0,
  },
  primaryAction: {
    // name: 'ElectrocardioFlama',
    // type: ActionType.PROJECTILE,
    // damage: 30,
    // cooldown: 0.5,
    // maxDistance: 40,
    // sound: 'hospital.ogg',
    // color: '#ff1e00',
    // projectile: {
    //   radius: 0.4,
    //   speed: 25,
    // },
    name: 'ElectrocardioFlama',
    type: ActionType.RAYCAST,
    damage: 20,
    cooldown: 0.3,
    maxDistance: 15,
    burstCount: 5,
    burstInterval: 1,
    sound: 'hospital2.ogg',
    color: '#ff1e00',
  },
  secondaryAction: {
    name: 'Sacar los Prohibidos',
    type: ActionType.SELF_HEAL,
    damage: -150,
    cooldown: 12.0,
    duration: 4,
    maxDistance: 0,
    sound: 'prohibidos.ogg',
    speedModifier: 0.5,
  },
  meleeAction: {
    name: 'Melee',
    type: ActionType.MELEE,
    damage: 20,
    cooldown: 0.8,
    maxDistance: 3,
    sound: 'slap.ogg',
  },
  voiceLines: {
    spawn: 'godinez_ready.ogg',
    death: 'godinez_down.ogg',
  },
  modelPath: '/models/adventurers/Characters/gltf/Mannequin_Medium.glb',
  renderMode: 'adventurer',
  animations: {
    idle: AdventurerAnimation.IDLE_A,
    run: AdventurerAnimation.RUNNING_A,
    shoot: AdventurerAnimation.RANGED_1H_SHOOT,
    jump: AdventurerAnimation.JUMP_START,
    jumpIdle: AdventurerAnimation.JUMP_IDLE,
    jumpLand: AdventurerAnimation.JUMP_LAND,
    death: AdventurerAnimation.DEATH_A,
    hitReact: AdventurerAnimation.HIT_A,
  },
  weapon: {
    modelPath: '/models/weapons/godinez.glb',
    scale: 0.15,
    position: [0.4, -0.3, -0.6],
    rotation: [0, Math.PI, 0],
    barrelPosition: [0, 0.05, -0.3],
  },
  secondaryWeapon: {
    modelPath: '/models/weapons/Hands.glb',
    scale: 1,
    position: [0, -0.4, -0.5],
    rotation: [0, Math.PI, 0],
    barrelPosition: [0, 0.05, -0.3],
  },
  thirdPersonWeapon: {
    modelPath: '/models/weapons/godinez.glb',
    scale: 0.08,
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    bone: 'handslotr',
  },
  thirdPersonSecondaryWeapon: {
    modelPath: '/models/weapons/Hands.glb',
    scale: 1.0,
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    bone: 'handslotr',
  },
};
